import { accountingDate, yearMonth } from "@waltning/core/date";
import { describe, expect, it } from "vitest";
import {
  enterDay,
  enterMonth,
  goToPage,
  type PagerState,
  pagerStateParams,
  parsePagerState,
  periodLabel,
  search,
  step,
  stepUnitOf,
} from "./pager-date.ts";

const TODAY = accountingDate("2026-09-08");
const on = (date: string, page: PagerState["page"] = "list"): PagerState => ({
  date: accountingDate(date),
  page,
  query: null,
});

describe("stepUnitOf", () => {
  it("steps a year on Months and a month everywhere else", () => {
    // An arrow that moved a month on Months would scroll a list of months by
    // one of its own rows: the reader steps and sees almost the same page.
    expect(stepUnitOf("months")).toBe("year");
    for (const page of ["summary", "list", "calendar"] as const) {
      expect(stepUnitOf(page)).toBe("month");
    }
  });
});

describe("step", () => {
  it("moves one month on the day pages", () => {
    expect(step(on("2026-09-08"), -1).date).toBe("2026-08-08");
    expect(step(on("2026-09-08"), 1).date).toBe("2026-10-08");
  });

  it("moves a whole year on Months", () => {
    expect(step(on("2026-09-08", "months"), -1).date).toBe("2025-09-08");
  });

  it("clamps a day past the end of the month it lands in", () => {
    // 31 January stepped forward is 28 February, not 3 March. `Date.UTC` rolls
    // the overflow into the next month, which makes one press skip a month —
    // and skip it only sometimes, which is the shape of a bug nobody
    // reproduces.
    expect(step(on("2026-01-31"), 1).date).toBe("2026-02-28");
    expect(step(on("2026-03-31"), -1).date).toBe("2026-02-28");
  });

  it("keeps the day where the month is long enough", () => {
    expect(step(on("2026-01-15"), 1).date).toBe("2026-02-15");
  });

  it("crosses a year boundary", () => {
    expect(step(on("2026-12-08"), 1).date).toBe("2027-01-08");
    expect(step(on("2026-01-08"), -1).date).toBe("2025-12-08");
  });

  it("never changes the page", () => {
    expect(step(on("2026-09-08", "calendar"), 1).page).toBe("calendar");
  });
});

describe("enterMonth", () => {
  it("lands on the month's newest day, not its first", () => {
    // The list is reverse-chronological: landing on the 1st puts the reader at
    // the end of the month with the whole of it behind them.
    expect(enterMonth(on("2026-09-08"), yearMonth("2026-08"), TODAY).date).toBe("2026-08-31");
    expect(enterMonth(on("2026-09-08"), yearMonth("2026-02"), TODAY).date).toBe("2026-02-28");
  });

  it("lands on today when the month is the current one", () => {
    // Today is where the current month's newest row is; 30 September is a day
    // that has not happened.
    expect(enterMonth(on("2026-03-04"), yearMonth("2026-09"), TODAY).date).toBe("2026-09-08");
  });

  it("lands on the last day of a month in a future year", () => {
    expect(enterMonth(on("2026-09-08"), yearMonth("2027-04"), TODAY).date).toBe("2027-04-30");
  });
});

describe("enterDay and goToPage", () => {
  it("keeps the date when only the page changes, which is the whole point", () => {
    const state = goToPage(on("2026-05-25", "list"), "calendar");
    expect(state).toEqual({ date: "2026-05-25", page: "calendar", query: null });
  });

  it("keeps the page when only the day changes", () => {
    expect(enterDay(on("2026-09-08", "calendar"), accountingDate("2026-05-25"))).toEqual({
      date: "2026-05-25",
      page: "calendar",
      query: null,
    });
  });
});

describe("periodLabel", () => {
  it("gives the month and its year as parts, in the current year", () => {
    expect(periodLabel(on("2026-09-08"))).toEqual({
      unit: "month",
      month: "2026-09",
      year: 2026,
    });
  });

  it("gives the same two parts once you have stepped out of the year", () => {
    expect(periodLabel(on("2024-03-04"))).toEqual({
      unit: "month",
      month: "2024-03",
      year: 2024,
    });
  });

  it("says the year on Months, where the year is the period", () => {
    expect(periodLabel(on("2026-09-08", "months"))).toEqual({ unit: "year", year: 2026 });
  });

  it("hands back parts, never a formatted string", () => {
    // `packages/client` may not import `packages/ui`, so it cannot know a
    // month's name in the reader's language — and must not guess at one.
    const label = periodLabel(on("2026-09-08"));
    expect(JSON.stringify(label)).not.toContain("September");
  });
});

describe("parsePagerState", () => {
  it("reads a link the agent could hand you", () => {
    // S03's "see them in the ledger" is this URL, and it must land on the day
    // it names rather than on the screen's default.
    expect(parsePagerState({ view: "list", date: "2026-05-25" }, TODAY)).toEqual({
      page: "list",
      date: "2026-05-25",
      query: null,
    });
  });

  it("lands on the summary when the view names nothing", () => {
    // A URL is typed by people and generated by models. An unknown view must
    // land somewhere sensible rather than render nothing.
    expect(parsePagerState({ view: "ledger" }, TODAY).page).toBe("summary");
    expect(parsePagerState({}, TODAY).page).toBe("summary");
  });

  it("lands on today when the date is not a real calendar day", () => {
    // Shape alone is not enough: 2026-02-30 matches YYYY-MM-DD and is not a
    // day, which is exactly the kind of date a generated link produces.
    expect(parsePagerState({ date: "2026-02-30" }, TODAY).date).toBe(TODAY);
    expect(parsePagerState({ date: "not-a-date" }, TODAY).date).toBe(TODAY);
    expect(parsePagerState({}, TODAY).date).toBe(TODAY);
  });

  it("round-trips through the parameters it writes", () => {
    const state = { page: "calendar", date: accountingDate("2024-03-04"), query: null } as const;
    expect(parsePagerState(pagerStateParams(state), TODAY)).toEqual(state);
  });
});

/**
 * S04 §7: the search *"holds across the pages the way the date does"*. So it
 * travels in the state the URL carries, and every move preserves it — a query
 * dropped by a swipe would make Calendar and Months answer §7's *how often, and
 * when* about a different question than the one the reader asked.
 */
it("carries the query through a step, a page change and a jump", () => {
  const searching: PagerState = { ...on("2026-09-08", "list"), query: "market" };
  expect(step(searching, -1).query).toBe("market");
  expect(goToPage(searching, "calendar").query).toBe("market");
  expect(enterDay(searching, accountingDate("2021-03-02")).query).toBe("market");
  expect(enterMonth(searching, yearMonth("2024-03"), TODAY).query).toBe("market");
});

/**
 * **A blank query is no query.** `?q=` and `?q=%20` arrive as strings; filtering
 * by the empty string matches every row while drawing a chip that says the
 * screen is narrowed. Folded to `null` where the URL is read, so nothing
 * downstream has to remember.
 */
it.each(["", "   ", "\t"])("reads %o as no search at all", (raw) => {
  expect(parsePagerState({ view: "list", date: "2026-09-08", q: raw }, TODAY).query).toBeNull();
});

it("trims a query rather than searching for the spaces", () => {
  expect(parsePagerState({ q: "  market  " }, TODAY).query).toBe("market");
});

/**
 * **The empty string, not an absent key.** `setParams` merges, so a cleared
 * search that wrote nothing would leave the old `q` in the URL — the chip would
 * go and the filter would stay.
 */
it("writes a cleared search as a parameter, not as an omission", () => {
  expect(pagerStateParams(on("2026-09-08")).q).toBe("");
  expect(pagerStateParams(search(on("2026-09-08"), "market")).q).toBe("market");
});

it("round-trips a search through the parameters it writes", () => {
  const state = search(on("2024-03-04", "calendar"), "market");
  expect(parsePagerState(pagerStateParams(state), TODAY)).toEqual(state);
});
