import { expect, it } from "vitest";
import { FIRST_YEAR, pageOf, stepYearPage, yearPage } from "./year-pages.ts";

const THIS_YEAR = 2026;

it("opens on this year and the eight before it", () => {
  const page = yearPage(2026, THIS_YEAR);
  expect(page.years).toEqual([2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]);
  expect(page.label).toBe("2018 \u2013 2026");
  expect(page.hasNewer).toBe(false);
});

/**
 * **Counted back from this year, not forward from 1900.** Forward from the
 * floor, (2026 − 1900) / 9 is exactly 14 — which lands 2026 alone on a page of
 * its own. The one year that must never be alone is this one.
 */
it("never leaves this year alone on a page", () => {
  expect(yearPage(THIS_YEAR, THIS_YEAR).years.length).toBe(9);
});

/**
 * **Aligned to the floor, not to the focus year.** A window centred on whatever
 * year is open would shift under the reader on every step — page back and
 * forward and you would not land where you started.
 */
it("returns you to the page you left", () => {
  const back = stepYearPage(2026, -1, THIS_YEAR);
  expect(yearPage(back, THIS_YEAR).years).toContain(2017);
  const forward = stepYearPage(back, 1, THIS_YEAR);
  expect(yearPage(forward, THIS_YEAR).years).toEqual(yearPage(2026, THIS_YEAR).years);
});

it("stops at 1900 in both the page and the step", () => {
  const first = yearPage(FIRST_YEAR, THIS_YEAR);
  expect(first.years[0]).toBe(1900);
  expect(first.hasOlder).toBe(false);
  // The oldest page is the short one — 2026 back to 1900 is not a multiple of
  // nine, and the remainder belongs where shortness costs nothing.
  expect(first.years.length).toBeLessThanOrEqual(9);
  // Stepping back from the floor stays on the floor rather than offering 1891.
  expect(stepYearPage(1901, -1, THIS_YEAR)).toBe(FIRST_YEAR);
});

it("refuses to page past the year we are in", () => {
  expect(yearPage(2026, THIS_YEAR).hasNewer).toBe(false);
  expect(stepYearPage(2026, 1, THIS_YEAR)).toBe(THIS_YEAR);
});

it("clamps a year from outside the range rather than computing a page for it", () => {
  // A URL is typed by people and generated by models (`parsePagerState`'s own
  // reasoning); 1743 and 9999 both have to land somewhere sensible.
  expect(yearPage(1743, THIS_YEAR).years[0]).toBe(FIRST_YEAR);
  expect(yearPage(9999, THIS_YEAR).years).toContain(THIS_YEAR);
});

it("counts pages from the floor", () => {
  expect(pageOf(THIS_YEAR, THIS_YEAR)).toBe(0);
  expect(pageOf(2018, THIS_YEAR)).toBe(0);
  expect(pageOf(2017, THIS_YEAR)).toBe(1);
});
